stages:
  - test

test:
  image: alpine:3.15
  stage: test
  before_script:
    - export PATH="/root/.cask/bin:$PATH"
  script:
  - apk update && apk add openssh make git curl python3 emacs openssh bash git stow
  - git clone https://github.com/cask/cask ~/.cask
  - cask install
  - cask exec ert-runner
